# Generated by Django 4.2 on 2024-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='empty', max_length=400),
            preserve_default=False,
        ),
    ]
